### ISSUE TITLE
M8s+ S812 android box AML 2.0.0

### ISSUE THREAD

**Issue by stupin1932** [AlexELEC/AlexELEC-AML#1]
Hello Alex,
i test your latest build for S812 android box on my M8s+ and everything is ok..But i can report 2 problems:
1. wired internet not working (always show dhcp  active with your ip adresses but wired internet not working)
2.i use pvr client vu+/enigma2 and it working ok and starting on aeon nox skin but on others skin it wont start when i turn box ON)i need everytime in addons enable/disable pvr client to start working
Thank you for this excellent job and i hope that you will fix this problem soon and maybe publish for my box m8s+ S812  android box....Thanks!!

**Comment by stupin1932** [comment]
Alex,
I found new issue:
OptionSWITCH  BOOT THE ANDROID dont work...always boot to alexelex on sdcard

**Comment by AlexELEC** [comment]
Hello,
Well ... The system was made for a specific device ([QINTEX Q812](http://qintexworld.com/showgoods/898.html)) and everything works.
Later, I will do for M8S +

**Comment by stupin1932** [comment]
thank you for answer.....i wait your build for m8s+....greetings from
Croatia

2016-11-26 18:26 GMT+01:00 Alexandr <notifications@github.com>:

**Comment by stupin1932** [comment]
Alex,
can you use in your future  build for m8s+ skin confluence extended for setup automatic load vu+/enigma2 pvr client?thanks!

**Comment by stupin1932** [comment]
Hello Alex,
when will be realise alexelec for S812 M8S+?
Thanks for excellent work!!

**Comment by devrosx** [comment]
hello, im also interested for S812 M8S+ openelec build

thanks

**Comment by AlexELEC** [comment]
Hello,
I have not tested the system, try ...
https://github.com/AlexELEC/AlexELEC-AML/releases/tag/2.1.4-M8SPlus

**Comment by stupin1932** [comment]
Hello Alex,
everything working super......

LAN 1000- working
remote-working
switch to android-working
live tv-working

Thanks again for excellent work....

2017-01-13 15:12 GMT+01:00 Alexandr <notifications@github.com>:

**Comment by gogenzuller** [comment]
Yes! Thanks Alex! S812 M8S+ works fine on my Acemax KII.
Only T3 airmouse+keboard not work. Wireless keyboard Logitech K400r works well. IR remote too. But T3, which working well on android, in alexelec works only in IR mode, not wi-fi.

**Comment by dankec2000** [comment]
Works great on my Acemax M8S+, but Bluetooth is not working. It's working fine on image found here: http://amlinux.ru/image/8xx/7.0.2/ (Libreelec with kodi 16.1) so maybe this could be used.

**Comment by kid666** [comment]
I launch Game RetroArch from shutdown menu, I see roms but with RC and keyboard I don't move anything, it's all freeze an i must unplug. Bluetooth is not working.

**Comment by dankec2000** [comment]
2.1.8 for M8S+ soon?

**Comment by AlexELEC** [comment]
added M8S and M8S+ (Almogic S812):
https://github.com/AlexELEC/AlexELEC-AML/releases/tag/2.1.8
**systems are not tested**

**Comment by littletvbox** [comment]
HI Alex
Much appreciated. M8S+ wifi isnt working and once its power off it does not turn on back from the remote control
Orignal M8S+  is based on BCM4335 wifi module ( I think your build supports AP6330)
Can you please build one for BCM4335 wifi as well. I can share the driver or kernel files 
Also,attached is the last fully working Libreelec version 7.0.2 ( https://mega.nz/#!jVVHFTZR!oMY4JGFrcham42yPudGTLNra9gPQxG-ebMzm8gHnzCY )
Hope to hear from you soon

**Comment by dankec2000** [comment]
Micky84, I have nothing against M8S+ version with BCM4335, but you're not telling the truth:

Original M8S+ (Acemax) don't come with BCM4335 (version with BCM4335 is clone!) but with AP6330, as you've been already told on Libreelec forum.

So, please, stop spreading disinformation.

**Comment by Micky84** [comment]
Hi mate

Sorry but I think you have earlier versions of M8S+and there is no need to get over excited. I had once seen the thread you created onfreaktab and the picture that you put in was a picture of Clone/copy board of M8S+

Before you jumping on to conclusion, please get the facts right, Orignally m8s+ was produced by Videostrong after success of M8S by Shiningstar/worth (Wifi chip for M8S is AP6330 however they are only accepting bulk order for 500 pieces and there are a lot of clones available in market)

Initial Versions of M8s+ had AP6330 Wifi however from last more than 6 month the wifi chip being used is BCM4335 (Broadcomm chip)

If you need further clarification, please contact ACEMAX  (I deal with the owner, Ken from ACEMAX on everyday basis)

I hope this will show you some light

**Comment by dankec2000** [comment]
As you said: "Initial Versions of M8s+ had AP6330 Wifi" so one is original! :). Thanks god, I sold my M8S+ clone with BCM4335 because it was full of bugs (it even came with no red LED!) and unstable and bought good old M8S+ with Ap6330 and no issues at all! At least, most of other 812 devices have the same ap6330 so I assume that support will be always better than for bcm4335. I suggest you to sold yours also and buy other box.

**Comment by Micky84** [comment]
HI mate

The one you posted picture on freaktab was NEVER a ACEMAX m8S+ (it was a cheap copy version; not from Acemax)

Initially for few weeks the wifi used for ACEMAX M8S+ AP6330 but at later stage they changed to BCM 4335 and up till today all ACEMAX M8S+ has BCM 4335 wifi chip on the board

I have over 13 of these boxes in house and with the family. You can check with ACEMAX they are not doing AP6330 wifi in their m8s+ from more than 7-8 months so even if i wish its not possible as  only a few production batches in the beginning has wifi AP6330

Its just you were not aware of the fact so i thought of sharing this with you. You are more than welcome to confirm the same from Ken (Acemax)

So if we can have support for ACEMAX m8S+ with BCM 4335 wifi that would be good as well as a lot of users are using ACEMAX M8S+ boxes
