### ISSUE TITLE
S805 MXQ_V20 -  not booting

### ISSUE THREAD

**Issue by ricardojlrufino** [AlexELEC/AlexELEC-AML#11]
Hi

I am not able to boot the model: S805 MXQ_V20.
I also did several tests with several images of: mxqproject.com
And one that worked was: LibreELEC-S805.m201d.arm-7.0.3.3c.img
> http://kszaq.libreelec.tv/s805/7.0.3.3/SD%20or%20Update/LibreELEC-S805.m201d.arm-7.0.3.3c.img.gz

On the board is written: S805Q V2.0 (2016.08.11)

**Comment by AlexELEC** [comment]
Hi,
On your board likely 512MB RAM.
You need this system: AlexELEC-S805.MXQ_V31.arm-2.2.3

**Comment by ricardojlrufino** [comment]
hi,
Thank you, it worked

**Comment by ricardojlrufino** [comment]
Do you have any tips for booting Linux / Ubuntu. I wanted to run a server.

I tried several versions but none worked.

**Comment by AlexELEC** [comment]
No. I was not interested.
