### ISSUE TITLE
AlecElec  M8S  S812

### ISSUE THREAD

**Issue by dbkalyan** [AlexELEC/AlexELEC-AML#17]
I have downloaded zip file "AlexELEC-S812.M8S.arm-2.2.2.img.gz" for my M8S box.  Having issues installing it. 
After downloading and unzipping the file, I tried dual boot my box with SD Card. But it will not work. Just shows Logo only.  Does it needs a dtb.img file as well?  I also notice recent updates have files for M8Splus only.  "AlexELEC-S812.M8SPlus.arm-2.2.4.img.gz" Will this work on M8S box?
And for curiosity sake What is "Source code (zip)" which is on the list.

**Comment by AlexELEC** [comment]
AlexELEC-S812.M8S.arm-2.2.2.img.gz - You need to uncompress this file and write the image (* .img) to the SD card using [Win32DiskImager](https://sourceforge.net/projects/win32diskimager/).

Source code (zip) - this is the source code of the system for self-assembly.

**Comment by dbkalyan** [comment]
Thanks. I will try this out.

Sent from Yahoo Mail on Android 
 
  On Mon, 15 May 2017 at 3:37 AM, Alexandr<notifications@github.com> wrote:   
AlexELEC-S812.M8S.arm-2.2.2.img.gz - You need to uncompress this file and write the image (* .img) to the SD card using Win32DiskImager.

Source code (zip) - this is the source code of the system for self-assembly.

**Comment by nik-ii** [comment]
Could you provide a 2.2.4/2.2.5 M8S release please?

**Comment by AlexELEC** [comment]
M8S will be in the release 2.2.5

**Comment by abraaocaldas** [comment]
There is any way to install it to the internal storage?

**Comment by AlexELEC** [comment]
@abraaocaldas
Yes. You can install with "nand-install" command from console or [from GUI](http://www.alexelec.in.ua/wp-content/uploads/image/2017/05/sys-224-01.jpg).

**Comment by nik-ii** [comment]
Thanks for the Image! Keep up the great work!
