### ISSUE TITLE
Add support for PPSSPP standalone?

### ISSUE THREAD

**Issue by shantigilbert** [AlexELEC/AlexELEC-AML#2]
Is there a possibility to add support for PPSSPP standalone? the libretro core is slower in many ways to the standalone, I have almost been successful in making it work on a s905, but most roms don't load and those that do load run very slow, and sound doesn't work.

I extracted the binaries from the Odroic C2 which also uses a S905, so I know it can work on a S905 but not sure how to.

**Comment by AlexELEC** [comment]
I do not see the need. I think they work the same way. And with a sound that's all right. See the tenth minute: https://www.youtube.com/watch?v=eQm4ux1ss8k

**Comment by shantigilbert** [comment]
Thanks for the reply, I have tried back to back (in another device) on the several games and the standalone gets about 5-10 FPS more than the Libretro core.
