### ISSUE TITLE
MXIII-G after shutdown it's impossible to restart and doesn't turn on with rc

### ISSUE THREAD

**Issue by kid666** [AlexELEC/AlexELEC-AML#21]
I've MXIII-G android box and i've installed M8SPro AlecELEC version. It's work fine but if I shut down the box it's impossible to restart with physical button press or remote control, I must remove power cable. The remote control is unusable to turn on the box. Is it possible remove this issue? There are some config files to edit manually...
Thanks in advance

**Comment by AlexELEC** [comment]
Hi,
I can not help you. I do not have MXIII-G and even M8SPlus.

**Comment by kid666** [comment]
You have released v.2.23/v.2.21 for MXIII-G, that's working very well...

**Comment by AlexELEC** [comment]
OK. I will later make version 2.2.5 for MXIII-G.

**Comment by kid666** [comment]
Thanks very much...

**Comment by kid666** [comment]
Can you create a dbt file for update?

**Comment by AlexELEC** [comment]
In systems for SOC Amlogic S8xx, the device tree (dtb) is embedded in the kernel.

**Comment by AlexELEC** [comment]
Added AlexELEC-S812.MXIII_G.arm-2.2.5:
https://github.com/AlexELEC/AlexELEC-AML/releases/tag/2.2.5

**Comment by kid666** [comment]
thanks, I've installed and it works fine.
