### ISSUE TITLE
MXIII-G don't restart (phisycal or rc button)

### ISSUE THREAD

**Issue by kid666** [AlexELEC/AlexELEC-AML#3]
I've MXIII-G with 108L1 firmware and after i've installed  AlexELEC-S812.M8SPlus.arm-2.1.7 (and update to 2.19) power button on rc don't work, so I press power button to start box, but if I turned off by Libreelec shutdown menu it's impossible restart the box, phisycal button don't work, power on RC don't work, but LED is red. I unplug the box and then restart with phisycal button. If i start Android the phisycal and rc button work well. Any suggest?

**Comment by AlexELEC** [comment]
Try this version. I do not know will work or not.
https://mega.nz/#F!vFhFQIzb!w-LuDsQLj2gy3GKEGoXDgA

**Comment by kid666** [comment]
I've installed and finally phisycal and rc button work very well after restart.
BT don't works and I've must calibrate the screen, now the screen is centered but I'don't see the icon volume of Yamaha RX-V373 hdmi receiver. 
I try to connect PS3 controller on usb cable but don't work very well (only directional buttons sometimes, not start or select)...

**Comment by kid666** [comment]
It's possible you realeased MXIII-G 2.21?
v. 2.20 it works perfect.

**Comment by stupin1932** [comment]
and new release 2.2.1  for m8s+?

thanks!

2017-03-24 8:18 GMT+01:00 kid666 <notifications@github.com>:

**Comment by AlexELEC** [comment]
Added builds for MXIII-G & M8S Plus.

**Comment by kid666** [comment]
Thanks, it works very well.
