### ISSUE TITLE
Freezing on S812

### ISSUE THREAD

**Issue by sulfatchlorid** [AlexELEC/AlexELEC-AML#4]
when running Kodi while updating the library the cpu will probably overheat and AlexELEC will stop working.
It would be nice to have the option to reduce the max. CPU usage that means limit the CPU frequency.

**Comment by AlexELEC** [comment]
Create a file /storage/.config/autostart.sh:
```
#!/bin/sh
echo 1536000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
```
оr other processor frequency.

**Comment by sulfatchlorid** [comment]
That 's the solution. Thanks.

**Comment by kozi1980** [comment]
wifi not working for m8s+ with AlexElec s812 m8splus.arm 2.2.0.img.gz or tar. Do you have this software with zip? Or solution for wifi a few days? Thank you

**Comment by AlexELEC** [comment]
sorry. I do not have m8s+.

**Comment by kozi1980** [comment]
Maybe you can find solution the another versions?

**Comment by dankec2000** [comment]
kozi1980, which wifi do you have in your M8S+? AP6330 or other?

**Comment by kozi1980** [comment]
Yes, I have AP6330. Is there solution?

**Comment by dankec2000** [comment]
Try with 2.1.9. I think that a guy with BCM4330 persuaded Alex to put support for this wifi and to remove wide spreaded AP6330 from latest version. Alex, please return back AP6330 support (as in other versions)!

**Comment by kozi1980** [comment]
the same problem and with 2.1.9! not working wifi. tomorrow I will try older version. Thank you dankec2000 for your time
