### ISSUE TITLE
HDMI-CEC

### ISSUE THREAD

**Issue by mitch55500** [AlexELEC/AlexELEC-AML#44]
Hi Alex, 

Have you have uninstalled HDMI-CEC module on the 2.3.3 version (m8s+)?
I can't access to it?

And I don't find how to install it.

Regards, 

Sébastien

**Comment by AlexELEC** [comment]
Hi,
No, it's disabled. Go to the Kodi Settings - > Input

**Comment by mitch55500** [comment]
In "settings/System"? Because, I have already tried : There is nothing to activate.
