### ISSUE TITLE
X96 S905X 1/8GB randomly resets to defaults setting within 6 reboots.

### ISSUE THREAD

**Issue by Dynamodz** [AlexELEC/AlexELEC-AML#9]
X96 S905X 1/8GB randomly resets to defaults setting within 6 reboots.
- Tried the X96 image on several MicroSD (including internal NAND)
- only made few cosmetic changed to the build:
changed skin to aeon nox (preinstalled one)
turned off rss feed
turned off CEC settings

Symtoms of problem:
- it starts with ramdonly changing custom skin settings to default ones after each reboot
- when shutting down from the shutdown menu, it randomly brings u to the game menu instead of turning off
- after 6 reboots (including a hard reset, pulling power plug out) it gets totally back to default build with default skin and Russian Language.

**Comment by AlexELEC** [comment]
Hi,
I can not reproduce this problem in my box (X96 S905X 2/16GB).
Show the system log after a failure. http://forum.alexelec.in.ua/viewtopic.php?f=11&t=1002
